### ISSUE TITLE
Code block in readme

### ISSUE THREAD

**Issue by philchia** [cizixs/gohttp#2]
```go
log.Println("Like this")
```

**Comment by cizixs** [comment]
Hey, @philchia. I didn't quite get your point.
Can you point out the actual lines and issue?

**Comment by philchia** [comment]
Use ``` to quote your code block

**Comment by cizixs** [comment]
Markdown accepts two code block style: space/tab and \`\`\`, they both works fine except the first one can not specify code language, like \`\`\`go.

Here is the document: https://daringfireball.net/projects/markdown/syntax#precode. 

Thanks for the tip anyway, but I'm gonna leave the document the way it is.
